apiVersion: appstudio.redhat.com/v1alpha1
kind: ImageRepository
metadata:
  annotations:
    image-controller.appstudio.redhat.com/update-component-image: "true"
  labels:
    appstudio.redhat.com/application: serverless-operator-137
    appstudio.redhat.com/component: kn-plugin-event-test-wathola-forwarder-117
  name: kn-plugin-event-test-wathola-forwarder-117
spec:
  image:
    name: serverless-operator-137/kn-plugin-event-test-wathola-forwarder
    visibility: public
